# Generated by Django 2.1.7 on 2019-05-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190506_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
